/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { Canvas, useFrame, useThree } from 'react-three-fiber'        
import React, { useRef } from 'react'
import { useGLTF, 

 } from '@react-three/drei'


export default function Lives(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/heart/model.gltf')
 
  return (
    <group ref={group} {...props} dispose={null}>
        <mesh geometry={nodes.heart_teamRed.geometry} material={materials['Red.015']} rotation={[.5,0,0]} />
    </group>
  )
}

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/heart/model.gltf')